// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/proto/addressbook.proto

package com.grpc.soapbox.grpc.client.google.proto;

public interface BooksOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Books)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .Book arrayBooks = 1;</code>
   */
  java.util.List<com.grpc.soapbox.grpc.client.google.proto.Book> 
      getArrayBooksList();
  /**
   * <code>repeated .Book arrayBooks = 1;</code>
   */
  com.grpc.soapbox.grpc.client.google.proto.Book getArrayBooks(int index);
  /**
   * <code>repeated .Book arrayBooks = 1;</code>
   */
  int getArrayBooksCount();
  /**
   * <code>repeated .Book arrayBooks = 1;</code>
   */
  java.util.List<? extends com.grpc.soapbox.grpc.client.google.proto.BookOrBuilder> 
      getArrayBooksOrBuilderList();
  /**
   * <code>repeated .Book arrayBooks = 1;</code>
   */
  com.grpc.soapbox.grpc.client.google.proto.BookOrBuilder getArrayBooksOrBuilder(
      int index);
}
